#!/bin/sh

set -eu

PKG_DIR="pkg"
PROFILE_DIR="profile"

TARGET="${TARGET:-"$HOME"}"
PROFILE="${PROFILE:-"$(hostname)"}"

err() { echo "${0##*/}: $*" >&2; }
die() { err "$*" && exit 1; }

MODE="${1:-install}"

case "$MODE" in
install | uninstall) ;;
*) die "invalid mode" ;;
esac
[ ! -f "$PROFILE_DIR/$PROFILE" ] && die "no profile file found for this machine"

set -- stow --verbose --dir="$PKG_DIR" --target="$TARGET"
case "$MODE" in
install) set -- "$@" --restow ;;
uninstall) set -- "$@" --delete ;;
*) ;; # Unreachable
esac
while IFS= read -r line; do
    set -- "$@" "$line"
done <"$PROFILE_DIR/$PROFILE"

"$@"
