#!/bin/sh

set -eu

read -r one five fifteen _ </proc/loadavg

printf -- '%s\n' "one|float|${one}"
printf -- '%s\n' "five|float|${five}"
printf -- '%s\n' "fifteen|float|${fifteen}"
printf -- '%s\n' ""
