#!/bin/sh

set -eu

if network_data=$(ip route get 1); then
    read -r _ _ _ _ device _ local_ip _ <<EOF
${network_data}
EOF
    connected="true"
else
    device=""
    local_ip=""
    connected="false"
fi

printf -- '%s\n' "device|string|${device}"
printf -- '%s\n' "local_ip|string|${local_ip}"
printf -- '%s\n' "connected|bool|${connected}"
printf -- '%s\n' ""
