#!/bin/sh

set -eu

REPORT_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/wttr_report"
OUTDATED_REPORT_THRESHOLD=3600

WTTR_URL_BASE="${WTTR_URL:-https://wttr.in}"
WTTR_URL_FORMAT="%C%09%t%09%p\n"

is_report_outdated() { [ "$(($(date +%s) - $(date -r "$REPORT_FILE" +%s)))" -ge "$OUTDATED_REPORT_THRESHOLD" ]; }
write_report() { curl --max-time 5 --fail --silent "$WTTR_URL_BASE?format=$WTTR_URL_FORMAT" >"$REPORT_FILE"; }

[ ! -f "$REPORT_FILE" ] && write_report
is_report_outdated && write_report
IFS=$(printf '\t') read -r condition temperature precipitation <"$REPORT_FILE"

printf 'condition|string|%s\n' "$condition"
printf 'temperature|string|%s\n' "$temperature"
printf 'prciptation|string|%s\n' "$precipitation"
printf '\n'
