#!/bin/sh

is_text_file() { grep -qIF '' "$1"; }

case "$(file -bL --mime-type -- "$1")" in
image/* | video/*)
    mediainfo "$1"
    ;;
text/*)
    cat "$1"
    ;;
*)
    { is_text_file "$1" && cat "$1"; } || file -b "$1"
    ;;
esac

return 127
