#!/bin/sh

# shellcheck disable=SC2016

exec xidlehook \
    --not-when-fullscreen \
    --socket "$XIDLEHOOK_SOCK" \
    --timer 600 \
    'i3lock -i "$XDG_CACHE_HOME/lock.png"' \
    '' \
    --timer 3600 \
    'loginctl suspend' \
    ''
