set -g mode-keys vi
set -g renumber-windows on
set -g base-index 1
set -g focus-events on
set -g status-style fg=green
set -g window-status-current-style reverse
set -g status-right ''
bind B set -g status
