#!/bin/sh

WALLPAPER="$XDG_DATA_HOME/wallpaper"

kanshi &

printf '%s' "$WALLPAPER" | entr -nr \
    swaybg -m fill -i "$WALLPAPER" &

yambar &

mako &

swayidle -w &

foot -s &

/usr/libexec/xdg-desktop-portal &
/usr/libexec/xdg-desktop-portal-wlr &

pipewire &

syncthing &
