#!/bin/sh

WALLPAPER="$XDG_DATA_HOME/wallpaper"

kanshi &
yambar &
printf '%s' "$WALLPAPER" | entr -nr \
    swaybg -m fill -i "$WALLPAPER" &
mako &
swayidle -w &
pipewire &
/usr/libexec/xdg-desktop-portal &
/usr/libexec/xdg-desktop-portal-wlr &
mpd --no-daemon &
gpg-agent --no-detach &
foot -s &
syncthing &
