#!/bin/sh

## Layout ##

riverctl default-attach-mode bottom
riverctl focus-follows-cursor normal
riverctl default-layout rivercarro
rivercarro -per-tag -main-ratio 0.55 -inner-gaps 0 -outer-gaps 0 &

## Appearance ##

riverctl border-width 1
riverctl background-color 0x121212
riverctl border-color-focused 0x83a598
riverctl border-color-unfocused 0x504945
riverctl border-color-urgent 0xfb4934

export LOCK_INIT_COLOR="222222"
export LOCK_INPUT_COLOR="83a598"
export LOCK_FAIL_COLOR="fb4934"

## Cursor ##

riverctl hide-cursor timeout 10000
riverctl hide-cursor when-typing enabled
riverctl xcursor-theme Adwaita

## Rules ##

riverctl rule-add ssd

for app in \
    '2 % org.qutebrowser.qutebrowser' \
    '2 % Firefox' \
    '4 % Signal' \
    '4 % vesktop' \
    '4 % Mumble' \
    '5 % Thunderbird' \
    '8 % Gimp-*' \
    '8 % com.obsproject.Studio'; do
    IFS=' % ' read -r app_tag app_id <<EOF
$app
EOF
    riverctl rule-add -app-id "$app_id" tags "$((1 << (app_tag - 1)))"
done

## Mappings ##

riverctl map normal Super Return spawn "$TERMINAL"
riverctl map normal Super W spawn "$BROWSER"
riverctl map normal Super P spawn "fuzzel"
riverctl map normal Super E spawn "$TERMINAL $EDITOR"
riverctl map normal Super F spawn "$TERMINAL lf"
riverctl map normal Super V spawn "$TERMINAL pulsemixer"
riverctl map normal Super Q spawn "$TERMINAL ncmpcpp"
riverctl map normal Super N spawn "$TERMINAL newsraft"

riverctl map normal Super O spawn "screenshot -cm full"
riverctl map normal Super+Shift O spawn "screenshot -cm select"
riverctl map normal None Print spawn "screenshot -cm full"
riverctl map normal Shift Print spawn "screenshot -cm select"

riverctl map -repeat normal Super J focus-view next
riverctl map -repeat normal Super K focus-view previous
riverctl map -repeat normal Super+Shift J swap next
riverctl map -repeat normal Super+Shift K swap previous

riverctl map -repeat normal Super H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map -repeat normal Super L send-layout-cmd rivercarro "main-ratio +0.05"
riverctl map -repeat normal Super I send-layout-cmd rivercarro "main-count +1"
riverctl map -repeat normal Super D send-layout-cmd rivercarro "main-count -1"

riverctl map normal Super T send-layout-cmd rivercarro "main-location left"
riverctl map normal Super+Shift T send-layout-cmd rivercarro "main-location top"
riverctl map normal Super M send-layout-cmd rivercarro "main-location monocle"
riverctl map normal Super+Shift Return zoom
riverctl map normal Super B spawn "pkill yambar || yambar"

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super+Shift C close
riverctl map normal Super+Shift Space toggle-float
riverctl map normal Super+Shift F toggle-fullscreen

riverctl map normal Alt+Control Delete exit
riverctl map normal Alt+Control L spawn "lock-screen"

riverctl map normal Super U spawn "dm-pass"
riverctl map normal Super+Shift B spawn "makoctl -a"
riverctl map normal Super+Shift W spawn "swayimg --gallery ~/pictures/wallpapers"
riverctl map normal Super+Shift N spawn "dm-output"
riverctl map normal Super+Shift M spawn "dm-mount"

for mode in normal locked; do
    riverctl map -repeat "$mode" None XF86AudioRaiseVolume spawn "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
    riverctl map -repeat "$mode" None XF86AudioLowerVolume spawn "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%-"
    riverctl map "$mode" None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    riverctl map "$mode" None XF86AudioMicMute spawn "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"

    riverctl map "$mode" None XF86AudioPlay spawn "mpc toggle"
    riverctl map "$mode" None XF86AudioPrev spawn "mpc prev"
    riverctl map "$mode" None XF86AudioNext spawn "mpc next"
    riverctl map "$mode" None XF86AudioStop spawn "mpc stop"

    riverctl map -repeat "$mode" None XF86MonBrightnessUp spawn "brightnessctl s 10%+"
    riverctl map -repeat "$mode" None XF86MonBrightnessDown spawn "brightnessctl s 10%-"
done

for i in $(seq 1 9); do
    tags=$((1 << (i - 1)))

    riverctl map normal Super "$i" set-focused-tags "$tags"
    riverctl map normal Super+Shift "$i" set-view-tags "$tags"
    riverctl map normal Super+Control "$i" toggle-focused-tags "$tags"
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags "$tags"
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags "$all_tags"
riverctl map normal Super+Shift 0 set-view-tags "$all_tags"

riverctl map normal Super Tab focus-previous-tags
riverctl map normal Super+Shift Tab send-to-previous-tags

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

## Input ##

riverctl set-repeat 50 300

pointer="pointer-1739-0-Synaptics_TM3276-022"
riverctl input "$pointer" natural-scroll enabled
riverctl input "$pointer" tap enabled
riverctl input "$pointer" middle-emulation enabled
riverctl input "$pointer" disable-while-typing enabled
riverctl input "$pointer" disable-while-trackpointing enabled

riverctl input '*IBM_TrackPoint*' pointer-accel 0.5

## Autostart ##

"${0%/*}/autostart" &
