directory: ~/music/newdata
library: ~/music/library.db
plugins: bandcamp edit fetchart lastgenre mpdupdate scrub the zero

import:
  languages: en
  move: yes

match:
  preferred:
    countries: ["US", "GB|UK"]
    media: ["CD", "Vinyl", "Digital Media|File"]
    original_year: yes

paths:
  default: %the{$albumartist}/($year) $album/$disc.$track $title

per_disc_numbering: yes

edit:
  albumfields: album albumartist albumtype genre year
  itemfields: album albumartist artist genre title track year

fetchart:
  cover_format: JPEG
  maxwidth: 1200
  quality: 90
  sources: cover_art_url

scrub:
  auto: yes

the:
  a: no

zero:
  keep_fields: album albumartist albumartist_sort albumtype artist artist_sort day disc disctotal genre month title track tracktotal year
  update_database: true
