#!/bin/sh

set -eu

xrdb -merge "$XDG_CONFIG_HOME/X11/xresources"

picom --backend glx --vsync &
dunst &
pipewire &
pipewire-pulse &
wireplumber &
mpd --no-daemon &
gpg-agent --server --no-detach &

exec dbus-launch --exit-with-session dwm
