#!/bin/sh

xrandr --dpi 96

# shellcheck disable=SC1091
[ -f "$XDG_DATA_HOME/screenlayout" ] && . "$XDG_DATA_HOME/screenlayout"
[ -f "$XDG_DATA_HOME/wallpaper" ] && xwallpaper --zoom "$XDG_DATA_HOME/wallpaper"
[ -f "$XDG_CONFIG_HOME/X11/xresources" ] && xrdb -merge "$XDG_CONFIG_HOME/X11/xresources"

xinput set-prop "SOAI USB Gaming Mouse" "libinput Accel Profile Enabled" 0 1 0
xinput set-prop "SOAI USB Gaming Mouse" "libinput Accel Speed" 0

autostart="pipewire wireplumber pipewire-pulse udiskie dunst picom sxhkd dwmblocks"
for program in $autostart; do
    "$program" &
done >/dev/null 2>&1
