[theme]
theme = "semi-native"
[theme.overrides]
idle_fg = "#eeeeee"
good_fg = "#00ff00"
warning_fg = "#ffff00"
critical_fg = "#ff0000"
info_fg = "#eeeeee"

[[block]]
block = "net"
format = "$ip"
interval = 60
[block.theme_overrides]
idle_fg = "#00ff00"

[[block]]
block = "sound"
format = "VOL $volume.eng(w:2)|"

[[block]]
block = "battery"
device = "BAT0"
format = "BAT0 $percentage{ ($time_remaining.dur(hms:true))|}"
full_format = ""
missing_format = ""
interval = 60
[block.theme_overrides]
good_fg = "#eeeeee"

[[block]]
block = "battery"
device = "BAT1"
format = "BAT1 $percentage{ ($time_remaining.dur(hms:true))|}"
full_format = ""
missing_format = ""
interval = 60
[block.theme_overrides]
good_fg = "#eeeeee"

[[block]]
block = "temperature"
format = "{$average}C"
interval = 10

[[block]]
block = "load"
format = "$1m.eng(w:4)"
interval = 3

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%b %d %Y %H:%M:%S')"
interval = 1
[block.theme_overrides]
idle_fg = "#ffa500"
