#!/bin/sh

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}

# Display configuration
wlr-randr \
    --output eDP-1 --off \
    --output HDMI-A-2 --mode 1280x1024@75.025002 Hz

# Look and feel
[ -f "$XDG_DATA_HOME/wallpaper" ] && wbg "$XDG_DATA_HOME/wallpaper" &
xrdb -merge "$XDG_CONFIG_HOME/X11/xresources"

# Background services
yambar &
pipewire &
mpd --no-daemon &
lf -server &
foot --server &

# Write stdin to a status file
rm -f "$XDG_CACHE_HOME/dwl-info"
exec >>"$XDG_CACHE_HOME/dwl-info"
while IFS= read -r line; do
    printf '%s\n' "$line"
done
