#!/bin/sh
exec 2>&1
[ -r ./conf ] && . ./conf
[ -r "${XDG_CONFIG_HOME:-${HOME}/.config}/wlsunset/config" ] && . "${XDG_CONFIG_HOME:-${HOME}/.config}/wlsunset/config"
if [ "${use_location:-0}" -eq 1 ]; then
	set -- "-l" "${latitude:-39.9}" "-L" "${longitude:-116.3}"
else
	set -- "-S" "${sunrise:-06:30}" "-s" "${sunset:-18:30}" "-d" "${duration:-1800}"
fi
exec wlsunset -T "${high_temp:-6500}" -t "${low_temp:-4000}" -g "${gamma:-1.0}" "$@"
