#!/bin/sh

printf '<openbox_pipe_menu>\n'
for layout in "$HOME"/.local/bin/screenlayouts/*; do
    printf '  <item label="%s">\n' "${layout##*/}"
    printf '    <action name="Execute">\n'
    printf '      <execute>%s</execute>\n' "$layout"
    printf '    </action>\n'
    printf '  </item>\n'
done
printf '</openbox_pipe_menu>\n'
