#!/bin/sh

link_binary() {
	ln -sfT "$(cabal list-bin $1)" "$HOME/.cabal/bin/$1"
}

cd "$XDG_CONFIG_HOME/xmonad" && cabal build || exit
link_binary xmonad
link_binary xmobar-top
link_binary xmobar-bottom
