#!/bin/sh

while IFS= read -r file; do
    case "$1" in
    w)
        wallpaper-set "$file"
        ;;
    e)
        setsid -f gimp "$file"
        ;;
    y)
        xclip -sel clip -t image/png "$file"
        notify-send "nsxiv" "Copied <b>${file##*/}</b> to the clipboard."
        ;;
    esac
done
