[theme]
theme = "native"

[theme.overrides]
idle_fg = "#dddddd"
good_fg = "#00ff00"
warning_fg = "#ffa500"
critical_fg = "#ff0000"
info_fg = { link = "idle_fg" }

[[block]]
block = "net"
format = "$ip"
inactive_format = ""
interval = 10
[block.theme_overrides]
normal_fg = { link = "good_fg" }

[[block]]
block = "load"
format = "$1m.eng(w:4)"
interval = 3

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%b %d %Y %H:%M:%S')"
interval = 1
