bar:
  height: 24
  location: top
  margin: 6
  spacing: 8
  font: Hack:size=12
  foreground: ebdbb2ff
  background: 121212ff

  left:
    - river:
        anchors:
          - tag-base: &tag-base {margin: 3}
          - occupied-tag: &occupied-tag {text: "{id}*"}
          - empty-tag: &empty-tag {text: "{id}."}
          - focused-tag: &focused-tag {foreground: "ebdbb2ff"}
          - inactive-tag: &inactive-tag {foreground: "7c6f64ff"}
          - title: &title {text: "{title}", max: 80, margin: 4}
        content:
          map:
            conditions:
              id > 9: {empty: {}}
              focused && occupied: {string: {<<: [*tag-base, *focused-tag, *occupied-tag]}}
              focused && ~occupied: {string: {<<: [*tag-base, *focused-tag, *empty-tag]}}
              occupied: {string: {<<: [*tag-base, *inactive-tag, *occupied-tag]}}
              ~occupied: {string: {<<: [*tag-base, *inactive-tag, *empty-tag]}}
        title: {string: {<<: *title}}

  right:
    - pipewire:
        content:
          map:
            conditions:
              type == sink: {string: {text: "VOL {cubic_volume}%"}}
    - script:
        path: ~/.config/yambar/scripts/battery
        poll-interval: 60000
        content: {string: {text: "BAT {bat0_icon}{bat0_capacity}% {bat1_icon}{bat1_capacity}%"}}
    - script:
        path: ~/.config/yambar/scripts/loadavg
        poll-interval: 10000
        content: {string: {text: "{one} {five} {fifteen}"}}
    - clock:
        date-format: "%b %d"
        time-format: "%H:%M"
        content: {string: {text: "{date} {time}"}}
