separator: &separator {text: " | ", foreground: "7c6f64ff"}

bar:
  height: 18
  location: top
  font: Terminus:size=12
  foreground: ebdbb2ff
  background: 121212ff

  left:
    - river:
        anchors:
          - occupied-tag: &occupied-tag {text: " {id}*"}
          - empty-tag: &empty-tag {text: " {id}."}
          - urgent-tag: &urgent-tag {text: " {id}!"}
          - focused-tag: &focused-tag {foreground: "ebdbb2ff"}
          - other-tag: &other-tag {foreground: "7c6f64ff"}
          - title: &title {text: " {title}", max: 80}
        content:
          map:
            conditions:
              id > 9: {empty: {}}
              focused && occupied: {string: {<<: [*focused-tag, *occupied-tag]}}
              focused && ~occupied: {string: {<<: [*focused-tag, *empty-tag]}}
              urgent: {string: {<<: [*focused-tag, *urgent-tag]}}
              occupied: {string: {<<: [*other-tag, *occupied-tag]}}
              ~occupied: {string: {<<: [*other-tag, *empty-tag]}}
        title: {string: {<<: *title}}

  right:
    - network:
        anchors:
          - net-ipv4: &net-ipv4
              conditions:
                state == up: {string: {text: "{ipv4}"}}
        content:
          map:
            conditions:
              name == lo: {empty: {}}
              name == wlo1: {map: {<<: *net-ipv4}}
    - label:
        content: {string: {<<: *separator}}
    - pipewire:
        content:
          map:
            conditions:
              type == sink: {string: {text: "VOL {cubic_volume}%"}}
    - label:
        content: {string: {<<: *separator}}
    - battery:
        name: BAT1
        poll-interval: 60000
        content:
          map:
            default: {string: {text: "BAT {capacity}%"}}
            conditions:
              state == discharging: {string: {text: "BAT {capacity}% ({estimate})"}}
              state == unknown: {string: {text: "Unknown"}}
    - label:
        content: {string: {<<: *separator}}
    - script:
        path: /usr/local/bin/yambar-loadavg
        args: [-I, 10]
        content: {string: {text: "{one}"}}
    - label:
        content: {string: {<<: *separator}}
    - clock:
        date-format: "%b %d %Y"
        time-format: "%H:%M"
        content: {string: {text: "{date} {time}"}}
    - label:
        content: {string: {text: " "}}
