separator: &separator {text: " | ", foreground: "7c6f64ff"}
spacer: &spacer {text: " "}

bar:
  height: 18
  location: top
  font: Terminus:size=12
  foreground: ebdbb2ff
  background: 121212ff

  left:
    - label:
        content: {string: {<<: *spacer}}
    - river:
        anchors:
          - occupied-tag: &occupied-tag {text: "{id}* "}
          - empty-tag: &empty-tag {text: "{id}. "}
          - urgent-tag: &urgent-tag {text: "{id}! "}
          - focused-tag: &focused-tag {foreground: "fabd2fff"}
          - other-tag: &other-tag {foreground: "7c6f64ff"}
        content:
          map:
            conditions:
              id > 9: {empty: {}}
              focused && occupied: {string: {<<: [*focused-tag, *occupied-tag]}}
              focused && ~occupied: {string: {<<: [*focused-tag, *empty-tag]}}
              urgent: {string: {<<: [*focused-tag, *urgent-tag]}}
              occupied: {string: {<<: [*other-tag, *occupied-tag]}}
              ~occupied: {string: {<<: [*other-tag, *empty-tag]}}
        title: {string: {text: "{layout}"}}
    - label:
        content: {string: {<<: *separator}}
    - foreign-toplevel:
        content:
          map:
            conditions:
              activated: {string: {text: "{title}", max: 80}}

  right:
    - battery:
        name: BAT1
        poll-interval: 60000
        content:
          map:
            default: {string: {text: "BAT {capacity}%"}}
            conditions:
              state == unknown: {empty: {}}
              state == discharging: {string: {text: "BAT {capacity}% ({estimate})"}}
    - label:
        content: {string: {<<: *separator}}
    - script:
        path: /usr/local/bin/yambar-loadavg
        args: [-I, 10]
        content: {string: {text: "{one}"}}
    - label:
        content: {string: {<<: *separator}}
    - clock:
        date-format: "%b %d %Y"
        time-format: "%H:%M"
        content: {string: {text: "{date} {time}"}}
    - label:
        content: {string: {<<: *spacer}}
