separator-color: &separator-color {foreground: 7c6f64ff}
separator-left: &separator-left {string: {text: "", <<: *separator-color}}
separator-right: &separator-right {string: {text: "", <<: *separator-color}}
spacer: &spacer {string: {text: " "}}
sep-right: &sep-right
  spacing: 0
  items:
    - <<: *spacer
    - <<: *separator-right
    - <<: *spacer

bar:
  height: 14
  location: top

  font: Terminus:size=12

  foreground: ebdbb2ff
  background: 121212ff

  left:
    - label:
        content:
          <<: *spacer
    - river:
        anchors:
          - prefix: &river-prefix {string: {text: "{id}:"}}
          - urgent: &river-urgent {string: {text: "!"}}
          - focused: &river-focused {string: {text: "*"}}
          - name: &river-name
              map:
                conditions:
                  id == 1: {string: {text: "term"}}
                  id == 2: {string: {text: "www"}}
                  id == 3: {string: {text: "mus"}}
                  id == 4: {string: {text: "chat"}}
                  id == 5: {string: {text: "vol"}}
                  id == 6: {string: {text: "sys"}}
                  id == 7: {string: {text: ""}}
                  id == 8: {string: {text: ""}}
                  id == 9: {string: {text: ""}}
          - tag-spacer: &tag-spacer
              map:
                conditions:
                  id <= 8: {<<: *spacer}
        content:
          - map:
              conditions:
                state == urgent:
                  list:
                    spacing: 0
                    items:
                      - <<: *river-prefix
                      - <<: *river-name
                      - <<: *river-urgent
                      - <<: *tag-spacer
                state == focused:
                  list:
                    spacing: 0
                    items:
                      - <<: *river-prefix
                      - <<: *river-name
                      - <<: *river-focused
                      - <<: *tag-spacer
                occupied:
                  list:
                    spacing: 0
                    items:
                      - <<: *river-prefix
                      - <<: *river-name
                      - <<: *tag-spacer
        title:
          list:
            spacing: 0
            items:
              - map:
                  conditions:
                    layout != "":
                      list:
                        spacing: 0
                        items:
                          - <<: *spacer
                          - <<: *separator-left
                          - <<: *spacer
                          - string: {text: "{layout}"}
              - map:
                  conditions:
                    title != "":
                      list:
                        spacing: 0
                        items:
                          - <<: *spacer
                          - <<: *separator-left
                          - <<: *spacer
                          - string: {text: "{title}"}

  right:
    - network:
        content:
          map:
            conditions:
              name != lo:
                string: {text: "{ipv4}"}
    - label:
        content:
          list: *sep-right
    - pipewire:
        anchors:
          - prefix: &volume-prefix {string: {text: "VOL"}}
        content:
          map:
            conditions:
              type == "sink":
                list:
                  spacing: 0
                  items:
                    - <<: *volume-prefix
                    - <<: *spacer
                    - string: {text: "{cubic_volume}%"}
    - label:
        content:
          list: *sep-right
    - battery:
        anchors:
          - prefix: &battery-prefix {string: {text: "BAT"}}
        name: BAT0
        poll-interval: 60000
        content:
          map:
            default:
              list:
                spacing: 0
                items:
                  - <<: *battery-prefix
                  - <<: *spacer
                  - string: {text: "{capacity}% ({estimate})"}
            conditions:
              state != discharging:
                list:
                  spacing: 0
                  items:
                    - <<: *battery-prefix
                    - <<: *spacer
                    - string: {text: "{capacity}%"}
    - label:
        content:
          list: *sep-right
    - clock:
        date-format: "%b %d %Y"
        time-format: "%H:%M"
        content:
          string: {text: "{date} {time}"}
    - label:
        content:
          list: *sep-right
    - script:
        path: ~/.config/yambar/scripts/load
        poll-interval: 3000
        content:
          string: {text: "{one}"}
    - label:
        content:
          <<: *spacer
