directory: ~/music
library: ~/.local/share/beets/library.db
plugins: deezer spotify importreplace edit missing mpdupdate the lyrics zero lastgenre

match:
  preferred:
    countries: ['US', 'GB|UK']
    media: ['CD', 'Vinyl', 'Digital Media|File']
    original_year: yes

zero:
  fields: month day comments
  update_database: true

paths:
  default: %the{$albumartist}/($year) $album/$disc.$track $title

the:
  a: no

importreplace:
  replacements:
    - item_fields: title artist artist_sort artist_credit
      album_fields: album artist artist_sort artist_credit
      replace:
        '[\u2018-\u201B]': ''''
        '[\u201C-\u201F]': '"'
        '[\u2010-\u2015]': '-'
        '[\u2026]': '...'
    - item_fields: artist artist_sort artist_credit
      album_fields: artist artist_sort artist_credit
      replace:
        '\bYe\b': 'Kanye West'
        '\bZebrahead\b': 'zebrahead'
        'featuring': 'feat.'
        'Feat[.]': 'feat.'
        'ft[.]': 'feat.'

lyrics:
  sources: lrclib
