#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile"
elif [ -f "$HOME/.xprofile" ]; then
    . "$HOME/.xprofile"
fi

exec dbus-launch dwm
